name: CI (SPM)

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  xcode_spm:
    name: Xcode ${{ matrix.xcode }} (Swift Package)
    runs-on: macos-12
    strategy:
      matrix:
        xcode: ["14.1"]
      fail-fast: false
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app
    steps:
      - uses: actions/checkout@v3
      - run: ./test macos_xcodespm
      - run: ./test ios_xcodespm
      - run: ./test tvos_xcodespm
